model:
  base_learning_rate: 5e-05
  adjust_learning_rate: false
  find_unused_parameters: true
  #gradient_clip_algorithm: norm
  precision: 32-true
  #grad_clip: 0.5
  target: models.second_stage.fm_model_e2e_kl_repa_reg.ModelREPATeacher
  params:
    warmup_steps: 5000
    sr_loss_weight: 1.0
    sr_yol_loss_weight: 0.1
    min_lr_multiplier: 0.1
    grad_acc_steps: 1
    grad_acc_steps_ae: 1
    ae_loss_weight: 0.01
    only_decoder: false
    enc_scale: 1.0
    adjust_lr_to_batch_size: false
    add_projector: true
    loss_type: cos_sim
    add_norm: false
    latent_dim: 1024
    ctx_noise_exp: 1.0
    ctx_noise_prob: 0.75
    nan_debug: false
    sr_latents:
      - 4
    tokenizer_config:
      folder: /work/dlclarge2/faridk-diff_force/orbis/logs_tk/tk/2025-08-20T21-17-35_stage1_kl_192x336_DLC101600_dec_only
      ckpt_path: #checkpoints/last.ckpt
      only_decoder: true
    generator_config:
      target: networks.DiT.dit_sr_bn.STDiT
      params:
        max_num_frames: 64
        hidden_size: 64 #768
        depth: 6 #24
        num_heads: 16
        mlp_ratio: 4
        patch_size: 2
        input_size:
        - 18
        - 32
        in_channels: 256
        dropout: 0.0
        drop_ctx_rate: 0.0
        ctx_noise_aug_prob: 0.0
        ctx_noise_aug_ratio: 0.0
    teacher_config:
      target: models.second_stage.teacher_model.DistillationTeacher
      params:
        model_id: facebook/dinov3-vitl16-pretrain-lvd1689m
        revision: main
        device: cuda
        dtype: bf16
        reg_tokens: 4
        class_tokens: 1
        patch_size: 16

data:
  target: data.datamodule.DataModuleFromConfig
  params:
    batch_size: 2 #6 worked
    num_workers: 6
    train:
      target: data.custom_multiframe.MultiHDF5DatasetMultiFrame
      params:
        hdf5_paths_file: /work/dlcsmall1/faridk-datasets_ssd/bdd/train/train_bdd_day_clear_12k_5Hz_videos_640x360.txt
        size:
        - 288
        - 512
        num_frames: 3
    validation:
      target: data.custom_multiframe.MultiHDF5DatasetMultiFrameFromJSON
      params:
        samples_json: /work/dlcsmall1/faridk-datasets_ssd/bdd/val/selected_validation_next_frame.json
        size:
        - 288
        - 512
        num_frames: 3